use std::path::Path;

/// Integration test: load the real-world Chapel Hill binary and run TDD.
/// Requires `cache/chapel_hill.bin` to exist (generated by transit-prep).
#[test]
fn test_load_and_route_chapel_hill() {
    let bin_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("cache/chapel_hill.bin");

    if !bin_path.exists() {
        eprintln!(
            "Skipping test: {:?} not found. Run transit-prep first.",
            bin_path
        );
        return;
    }

    let data = std::fs::read(&bin_path).expect("Failed to read binary file");

    // Load data through the router's data module
    let prepared = transit_router::data::load(&data).expect("Failed to load binary data");

    // Verify basic counts
    assert!(prepared.num_nodes > 0, "Should have nodes");
    assert!(prepared.num_edges > 0, "Should have edges");
    assert!(prepared.num_stops > 0, "Should have stops");
    assert!(!prepared.patterns.is_empty(), "Should have patterns");
    assert!(!prepared.route_names.is_empty(), "Should have route names");

    eprintln!(
        "Loaded: {} nodes, {} edges, {} stops, {} patterns",
        prepared.num_nodes,
        prepared.num_edges,
        prepared.num_stops,
        prepared.patterns.len()
    );

    // Run TDD from a node near center of Chapel Hill
    // Snap to a node near UNC campus (35.91, -79.05)
    let source = transit_router::router::snap_to_node(&prepared, 35.91, -79.05);
    eprintln!(
        "Source node: {} at ({}, {})",
        source, prepared.nodes[source as usize].lat, prepared.nodes[source as usize].lon
    );

    // Run TDD at 8:00 AM (28800 seconds) on the first pattern
    let departure_time = 28800u32;
    let result = transit_router::router::run_tdd(&prepared, source, departure_time, 0, 60);

    // Count reachable nodes
    let reachable = result
        .iter()
        .filter(|r| r.arrival_delta != u16::MAX)
        .count();
    eprintln!("Reachable nodes: {} / {}", reachable, prepared.num_nodes);
    assert!(reachable > 0, "Should reach at least some nodes");

    // Source should be reachable with 0 travel time
    assert_eq!(
        result[source as usize].arrival_delta, 0,
        "Source should have zero arrival delta"
    );

    // Check some nodes have transit arrivals
    let transit_reached = result.iter().filter(|r| r.route_index != u32::MAX).count();
    eprintln!("Nodes reached via transit: {}", transit_reached);

    // Verify travel times are reasonable (< 2 hours from departure)
    for r in &result {
        if r.arrival_delta != u16::MAX {
            assert!(
                r.arrival_delta as u32 <= 7200,
                "Travel time {} exceeds max",
                r.arrival_delta
            );
        }
    }

    eprintln!("Integration test passed!");
}

/// Test that the router handles edge cases properly.
#[test]
fn test_router_edge_cases() {
    let bin_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("cache/chapel_hill.bin");

    if !bin_path.exists() {
        return;
    }

    let data = std::fs::read(&bin_path).unwrap();
    let prepared = transit_router::data::load(&data).unwrap();

    // Test with invalid pattern index (should not panic)
    let source = transit_router::router::snap_to_node(&prepared, 35.91, -79.05);
    let result = transit_router::router::run_tdd(&prepared, source, 28800, 999, 60);
    // Should still reach walking nodes
    let reachable = result
        .iter()
        .filter(|r| r.arrival_delta != u16::MAX)
        .count();
    assert!(
        reachable > 0,
        "Should still reach walking nodes with invalid pattern"
    );

    // Test at midnight (0 seconds)
    let result_midnight = transit_router::router::run_tdd(&prepared, source, 0, 0, 60);
    let reachable_midnight = result_midnight
        .iter()
        .filter(|r| r.arrival_delta != u16::MAX)
        .count();
    assert!(
        reachable_midnight > 0,
        "Should reach nodes even at midnight"
    );

    // Test at late time (23:59)
    let result_late = transit_router::router::run_tdd(&prepared, source, 86340, 0, 60);
    let reachable_late = result_late
        .iter()
        .filter(|r| r.arrival_delta != u16::MAX)
        .count();
    assert!(reachable_late > 0, "Should reach nodes even at late hour");

    eprintln!("Edge case tests passed!");
}
