[package]
name = "transit-router"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
transit-data = { path = "../transit-data" }
serde = { workspace = true }
serde_json = { workspace = true }
bytemuck = { workspace = true }
pco = "1"
rayon = "1.10"
radix-heap = "0.4.2"
chrono = { version = "0.4", default-features = false }

[dev-dependencies]
transit-prep = { path = "../transit-prep" }
flate2 = "1"
rand = "0.9"
rand_xoshiro = "0.7"
chrono = { version = "0.4", features = ["clock"] }
